#!/bin/sh

# start xen pv console if xen pv detected
case "$1" in
        start)
                echo "Checking if we need hvc0"
                grep -q hvc0 /proc/cmdline && /sbin/getty -L  hvc0 115200 vt100 || exit 0
                ;;
        stop)
		exit 0
                ;;
        restart)
                exit 0
		;;
esac


